-- 코드를 작성해주세요
WITH all_ids AS (
    SELECT ID
    FROM ECOLI_DATA
),

counts AS (
    SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID is NOT NULL
    GROUP BY PARENT_ID
)

# NULL 갑처리는 IFNULL, CASE, COALESCE로 가능
# SELECT a.ID, IFNULL(c.CHILD_COUNT, 0) AS CHILD_COUNT
SELECT a.ID, COALESCE(c.CHILD_COUNT, 0) AS CHILD_COUNT
FROM all_ids a
LEFT JOIN counts c
ON a.ID = c.ID
ORDER BY a.ID;