-- 코드를 입력하세요
WITH FH AS
( SELECT FLAVOR, TOTAL_ORDER
 FROM FIRST_HALF
), J AS
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT FH.FLAVOR
FROM FH JOIN J ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3 OFFSET 0;
;