-- 코드를 입력하세요

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '____-03%' and GENDER = 'W' and TLNO is not NULL
ORDER BY MEMBER_ID;













-- DATE_FORMAT 함수!!
# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') DATE_OF_BIRTH
# FROM MEMBER_PROFILE
# WHERE GENDER="W" and MONTH(DATE_OF_BIRTH)=3 and TLNO IS NOT NULL -- 문자에 "" 붙여야 함
# ORDER BY MEMBER_ID;