-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d')
AS PUBLISHED_DATE

FROM BOOK as B LEFT JOIN AUTHOR as A on A.AUTHOR_ID = B.AUTHOR_ID

WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC
;